version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bodytracker-postgres
    restart: always
    environment:
      POSTGRES_USER: bodytracker
      POSTGRES_PASSWORD: bodytracker
      POSTGRES_DB: bodytracker
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data


